import Nav from './Nav/Nav'
import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react';
import Toast from './Toast';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Profile Editing App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <Toast />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
